[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.9"
indoc = "2.0.5"
itertools = "0.13.0"
num = "0.4.3"
rayon = "1.10.0"
regex = "1.11.1"
sorted-vec = "0.8.5"
